baseURL = "https://testtesttesttesttesttest.netlify.com"
title = "Homepage"
copyright = "Copyright © 2018, Duan, Jieyi"
languageCode = "en-US" #ja-JP
theme = "indigo"
paginate = 3

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  Author = "Test"
  Description = "Description of website for head meta tag"
  Subtitle = "Making homepage"
  Avatar = "images/site-logo.svg"
  Biography = "A short description, a few sentences describing the author. Set the 'ShowBio' parameter to false to hide this."
  ShowBio = true
  PermalinkText = "🔗"

  # Contact/social-network identifiers for social icons
  EmailAddress = "email.address@example.com"

  
  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]
    EmailAddress = "email.address@example.com"
    FlickrUser = "FlickrUserName"
    GitHubUser = "GitHubUserName"
    TwitterUser = "TwitterUserName"
    MicroBlogUser = "MicroBlogUserName"
    Country = "CountryName"
    City = "CityName"
